### ISSUE TITLE
client.py 한글 지원 여부 검토

### ISSUE THREAD

**Issue by snoopspy** [netduck/codegate-beacon-flood#13]
한글 입력이 안되는 것 같은데 검토 바랍니다.

**Comment by AidenKim-com** [comment]
해당 이슈는 리눅스에서 어떤 입력기를 사용하느냐에 따라서 달라집니다.

fctix 한글 입력기를 사용할 경우엔 다음 글을 참고해서 문제를 해결할 수 있습니다. 
https://aidencom.tistory.com/1639

이와 같은 이슈는 이벤트에 활용할 PC에서 트러블 슈팅이 완료되었습니다.
